had_sfox_content_pipe:
  driver = pipe
  environment = HAD_SFOX_BSMTP=1:HAD_SFOX_QUEUE_ID_B64=${base64:$message_exim_id}:HAD_SFOX_SENDER_B64=${base64:$sender_address}:HAD_SFOX_RECIPIENTS_B64=${base64:$recipients}:HAD_SFOX_CLIENT_IP_B64=${base64:$sender_host_address}:HAD_SFOX_HELO_B64=${base64:$sender_helo_name}:HAD_SFOX_RECEIVED_PORT_B64=${base64:$received_port}
  message_prefix =
  message_suffix =
  use_bsmtp = true
  return_output
  temp_errors = 75:73
